package XMLandJSON.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptConvertor = createDescriptorForConvertor();
  /*package*/ final ConceptDescriptor myConceptJSON = createDescriptorForJSON();
  /*package*/ final ConceptDescriptor myConceptJSONAttribute = createDescriptorForJSONAttribute();
  /*package*/ final ConceptDescriptor myConceptJSONElement = createDescriptorForJSONElement();
  /*package*/ final ConceptDescriptor myConceptJSONField = createDescriptorForJSONField();
  /*package*/ final ConceptDescriptor myConceptXML = createDescriptorForXML();
  /*package*/ final ConceptDescriptor myConceptXMLAttribute = createDescriptorForXMLAttribute();
  /*package*/ final ConceptDescriptor myConceptXMLElement = createDescriptorForXMLElement();
  /*package*/ final ConceptDescriptor myConceptXMLField = createDescriptorForXMLField();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptConvertor, myConceptJSON, myConceptJSONAttribute, myConceptJSONElement, myConceptJSONField, myConceptXML, myConceptXMLAttribute, myConceptXMLElement, myConceptXMLField);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Convertor:
        return myConceptConvertor;
      case LanguageConceptSwitch.JSON:
        return myConceptJSON;
      case LanguageConceptSwitch.JSONAttribute:
        return myConceptJSONAttribute;
      case LanguageConceptSwitch.JSONElement:
        return myConceptJSONElement;
      case LanguageConceptSwitch.JSONField:
        return myConceptJSONField;
      case LanguageConceptSwitch.XML:
        return myConceptXML;
      case LanguageConceptSwitch.XMLAttribute:
        return myConceptXMLAttribute;
      case LanguageConceptSwitch.XMLElement:
        return myConceptXMLElement;
      case LanguageConceptSwitch.XMLField:
        return myConceptXMLField;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForConvertor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("XMLandJSON", "Convertor", 0x5340cbbc1593490dL, 0xa1b08191311313d1L, 0x587e888911637068L);
    b.class_(false, false, true);
    b.origin("r:5c201cd9-93b7-4be6-be1a-96463ad0e1c2(XMLandJSON.structure)/6376684244686827624");
    b.version(3);
    b.aggregate("XML", 0x587e88891163706bL).target(0x5340cbbc1593490dL, 0xa1b08191311313d1L, 0x3605bc724f528793L).optional(false).ordered(true).multiple(false).origin("6376684244686827627").done();
    b.aggregate("JSON", 0x587e88891163706dL).target(0x5340cbbc1593490dL, 0xa1b08191311313d1L, 0x3605bc724f561142L).optional(false).ordered(true).multiple(false).origin("6376684244686827629").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForJSON() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("XMLandJSON", "JSON", 0x5340cbbc1593490dL, 0xa1b08191311313d1L, 0x3605bc724f561142L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:5c201cd9-93b7-4be6-be1a-96463ad0e1c2(XMLandJSON.structure)/3892724652074996034");
    b.version(3);
    b.aggregate("elements", 0x3605bc724f57ff48L).target(0x5340cbbc1593490dL, 0xa1b08191311313d1L, 0x3605bc724f56397fL).optional(true).ordered(true).multiple(true).origin("3892724652075122504").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForJSONAttribute() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("XMLandJSON", "JSONAttribute", 0x5340cbbc1593490dL, 0xa1b08191311313d1L, 0x3605bc724f563980L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:5c201cd9-93b7-4be6-be1a-96463ad0e1c2(XMLandJSON.structure)/3892724652075006336");
    b.version(3);
    b.property("value", 0x3605bc724f563988L).type(PrimitiveTypeId.STRING).origin("3892724652075006344").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForJSONElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("XMLandJSON", "JSONElement", 0x5340cbbc1593490dL, 0xa1b08191311313d1L, 0x3605bc724f56397fL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:5c201cd9-93b7-4be6-be1a-96463ad0e1c2(XMLandJSON.structure)/3892724652075006335");
    b.version(3);
    b.aggregate("attributes", 0x3605bc724f56398eL).target(0x5340cbbc1593490dL, 0xa1b08191311313d1L, 0x3605bc724f563980L).optional(true).ordered(true).multiple(true).origin("3892724652075006350").done();
    b.aggregate("fields", 0x3605bc724f563990L).target(0x5340cbbc1593490dL, 0xa1b08191311313d1L, 0x3605bc724f563985L).optional(true).ordered(true).multiple(true).origin("3892724652075006352").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForJSONField() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("XMLandJSON", "JSONField", 0x5340cbbc1593490dL, 0xa1b08191311313d1L, 0x3605bc724f563985L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:5c201cd9-93b7-4be6-be1a-96463ad0e1c2(XMLandJSON.structure)/3892724652075006341");
    b.version(3);
    b.property("values", 0x3605bc724f56398aL).type(PrimitiveTypeId.STRING).origin("3892724652075006346").done();
    b.aggregate("attributes", 0x3605bc724f56398cL).target(0x5340cbbc1593490dL, 0xa1b08191311313d1L, 0x3605bc724f563980L).optional(true).ordered(true).multiple(true).origin("3892724652075006348").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForXML() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("XMLandJSON", "XML", 0x5340cbbc1593490dL, 0xa1b08191311313d1L, 0x3605bc724f528793L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:5c201cd9-93b7-4be6-be1a-96463ad0e1c2(XMLandJSON.structure)/3892724652074764179");
    b.version(3);
    b.aggregate("elements", 0x3605bc724f5287b6L).target(0x5340cbbc1593490dL, 0xa1b08191311313d1L, 0x3605bc724f528795L).optional(true).ordered(true).multiple(true).origin("3892724652074764214").done();
    b.alias("Create new XML document");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForXMLAttribute() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("XMLandJSON", "XMLAttribute", 0x5340cbbc1593490dL, 0xa1b08191311313d1L, 0x3605bc724f528794L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:5c201cd9-93b7-4be6-be1a-96463ad0e1c2(XMLandJSON.structure)/3892724652074764180");
    b.version(3);
    b.property("value", 0x3605bc724f538657L).type(PrimitiveTypeId.STRING).origin("3892724652074829399").done();
    b.alias("Create new XML attribute");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForXMLElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("XMLandJSON", "XMLElement", 0x5340cbbc1593490dL, 0xa1b08191311313d1L, 0x3605bc724f528795L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:5c201cd9-93b7-4be6-be1a-96463ad0e1c2(XMLandJSON.structure)/3892724652074764181");
    b.version(3);
    b.aggregate("attributes", 0x3605bc724f52b233L).target(0x5340cbbc1593490dL, 0xa1b08191311313d1L, 0x3605bc724f528794L).optional(true).ordered(true).multiple(true).origin("3892724652074775091").done();
    b.aggregate("fields", 0x3605bc724f52b235L).target(0x5340cbbc1593490dL, 0xa1b08191311313d1L, 0x3605bc724f54bc13L).optional(true).ordered(true).multiple(true).origin("3892724652074775093").done();
    b.alias("Create new XML element");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForXMLField() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("XMLandJSON", "XMLField", 0x5340cbbc1593490dL, 0xa1b08191311313d1L, 0x3605bc724f54bc13L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:5c201cd9-93b7-4be6-be1a-96463ad0e1c2(XMLandJSON.structure)/3892724652074908691");
    b.version(3);
    b.property("values", 0x3605bc724f54bc1cL).type(PrimitiveTypeId.STRING).origin("3892724652074908700").done();
    b.aggregate("attributes", 0x3605bc724f54bc16L).target(0x5340cbbc1593490dL, 0xa1b08191311313d1L, 0x3605bc724f528794L).optional(true).ordered(true).multiple(true).origin("3892724652074908694").done();
    b.alias("Create new XML field");
    return b.create();
  }
}
