package XMLandJSON.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class check_XMLElement_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public check_XMLElement_NonTypesystemRule() {
  }
  public void applyRule(final SNode xmlElement, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    if (isEmptyString(SPropertyOperations.getString(xmlElement, PROPS.name$MnvL))) {
      {
        final MessageTarget errorTarget = new NodeMessageTarget();
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(xmlElement, "XML Element name must be specified", "r:73577531-c3a6-480c-8444-5713fdd79d44(XMLandJSON.typesystem)", "7318856572702995282", null, errorTarget);
      }
    }
    if (SPropertyOperations.getString(xmlElement, PROPS.name$MnvL).length() <= 1) {
      {
        final MessageTarget errorTarget = new NodeMessageTarget();
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(xmlElement, "XML Element name must have at least 2 characters.", "r:73577531-c3a6-480c-8444-5713fdd79d44(XMLandJSON.typesystem)", "7318856572702484188", null, errorTarget);
      }
    }
    if (!(SPropertyOperations.getString(xmlElement, PROPS.name$MnvL).matches("^[a-zA-Z]*$"))) {
      {
        final MessageTarget errorTarget = new NodeMessageTarget();
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(xmlElement, "XML Element name can contain only letters.", "r:73577531-c3a6-480c-8444-5713fdd79d44(XMLandJSON.typesystem)", "7318856572704135322", null, errorTarget);
      }
    }
    for (SNode el : SLinkOperations.getChildren(SNodeOperations.getNodeAncestor(xmlElement, CONCEPTS.XML$U5, false, false), LINKS.elements$YyrS)) {
      if (SNodeOperations.isInstanceOf(el, CONCEPTS.XMLElement$5e)) {
        SNode node_el = (SNode) el;
        if (node_el != xmlElement && !(SPropertyOperations.getString(node_el, PROPS.name$MnvL).equals(SPropertyOperations.getString(xmlElement, PROPS.name$MnvL)))) {
          {
            final MessageTarget errorTarget = new NodeMessageTarget();
            IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(xmlElement, "Element name must be same as other elements in the XML structure.", "r:73577531-c3a6-480c-8444-5713fdd79d44(XMLandJSON.typesystem)", "961444738999175895", null, errorTarget);
          }
        }
      }
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.XMLElement$5e;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }
  private static boolean isEmptyString(String str) {
    return str == null || str.isEmpty();
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept XMLElement$5e = MetaAdapterFactory.getConcept(0x5340cbbc1593490dL, 0xa1b08191311313d1L, 0x3605bc724f528795L, "XMLandJSON.structure.XMLElement");
    /*package*/ static final SConcept XML$U5 = MetaAdapterFactory.getConcept(0x5340cbbc1593490dL, 0xa1b08191311313d1L, 0x3605bc724f528793L, "XMLandJSON.structure.XML");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink elements$YyrS = MetaAdapterFactory.getContainmentLink(0x5340cbbc1593490dL, 0xa1b08191311313d1L, 0x3605bc724f528793L, 0x3605bc724f5287b6L, "elements");
  }
}
